export enum QualityErrors {
  PHONE_NOT_VALID = 'PHONE_NOT_VALID',
  PHONE_IN_BLACKLIST = 'PHONE_IN_BLACKLIST',
  EMAIL_IN_BLACKLIST = 'EMAIL_IN_BLACKLIST',
  DUPLICATE = 'DUPLICATE',
  INTERNAL = 'INTERNAL',
}
